version: '3.7'
services:
   postgres:
      image: postgres:latest
      container_name: postgres
      restart: on-failure
      volumes:
         - postgres:/var/lib/postgresql/data
      environment:
         - POSTGRES_USER
         - POSTGRES_DATABASE
         - POSTGRES_PASSWORD
      build:
         dockerfile: Dockerfile.dev
      ports:
         - '5433:5433'
   pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin
      volumes:
         - pgadmin:/root/.pgadmin
      depends_on:
         - postgres
      ports:
         - '5050:80'
      links:
         - postgres:postgres
      environment:
         - PGADMIN_DEFAULT_EMAIL
         - PGADMIN_DEFAULT_PASSWORD
   api:
      container_name: api
      build:
         dockerfile: Dockerfile.dev
         context: ./api
      volumes:
         - /app/node_modules
         - ./api/:/app
      restart: on-failure
      command: npm run dev:windows
      links:
         - postgres:postgres
      ports:
         - '5000:5000'
      depends_on:
         - postgres
      environment:
         - POSTGRES_USER
         - POSTGRES_DATABASE
         - POSTGRES_PASSWORD
         - POSTGRES_HOST
         - POSTGRES_PORT

volumes:
   postgres: ~
   pgadmin: ~
